name: Continuous Integration

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and build
      run: |
        npm ci
        npm run build
        npm run build:tests
    - name: Lint and run unit tests
      run: |
        npm test
        npm run api-extractor
    - name: Run emulator-based integration tests
      run: |
        npm install -g firebase-tools
        npm run integration:emulator
